name: Test and Deploy
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
          
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip3 install pandas
          pip3 install sqlalchemy
          pip3 install requests
          pip3 install strings
          pip3 install re
          pip3 install html2text
          pip3 install bs4
          pip3 install mistletoe
          pip3 install numpy
          pip3 install plotly
          pip3 install flask
          pip3 install flask-wtf
          pip3 install flask-sqlalchemy
          pip3 install email-validator
          pip3 install flask_bcrypt
          
          
      - name: Lint with pycodestyle
        run: |
          pycodestyle --first *.py

      - name: Test with pytest
        run: |
          python3 -m pytest
